### ISSUE TITLE
between报错

### ISSUE THREAD

**Issue by chenhz2284** [dangdangdotcom/sharding-jdbc#103]
报错的sql为：
select * from pos where 1=1 and (gather_time between '2015-01-01' and '2015-01-02') and (partition_by between '20150101' and '20150102')

表结构如下：

	create table pos_20150101
	(
		id varchar(32) primary key,
		longitude double,
		latitude double,
		gather_time datetime,
		partition_by varchar(100)
	)
	engine=INNODB
	DEFAULT charset=gbk;
	
	
	create table pos_20150102
	(
		id varchar(32) primary key,
		longitude double,
		latitude double,
		gather_time datetime,
		partition_by varchar(100)
	)
	engine=INNODB
	DEFAULT charset=gbk;
	
	
	
	create table pos_20160101
	(
		id varchar(32) primary key,
		longitude double,
		latitude double,
		gather_time datetime,
		partition_by varchar(100)
	)
	engine=INNODB
	DEFAULT charset=gbk;
	
	
	
	create table pos_20160102
	(
		id varchar(32) primary key,
		longitude double,
		latitude double,
		gather_time datetime,
		partition_by varchar(100)
	)
	engine=INNODB
	DEFAULT charset=gbk;

partition_by 是分库分区键。

具体的代码见附件：

**Comment by chenhz2284** [comment]
[ModuloTableShardingAlgorithm.java.txt](https://github.com/dangdangdotcom/sharding-jdbc/files/303857/ModuloTableShardingAlgorithm.java.txt)
[ModuloDatabaseShardingAlgorithm.java.txt](https://github.com/dangdangdotcom/sharding-jdbc/files/303856/ModuloDatabaseShardingAlgorithm.java.txt)
[Main.java.txt](https://github.com/dangdangdotcom/sharding-jdbc/files/303858/Main.java.txt)

**Comment by jinfei21** [comment]
报错的信息可不可贴出来一下。

**Comment by chenhz2284** [comment]
![image](https://cloud.githubusercontent.com/assets/9113741/15985269/68a33532-301a-11e6-99ee-893bb80cba3f.png)
报错信息如图

**Comment by chenhz2284** [comment]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at java.util.Collections$UnmodifiableList.get(Collections.java:1211)
	at com.dangdang.ddframe.rdb.sharding.jdbc.AbstractShardingResultSet.<init>(AbstractShardingResultSet.java:46)
	at com.dangdang.ddframe.rdb.sharding.merger.iterator.IteratorResultSet.<init>(IteratorResultSet.java:35)
	at com.dangdang.ddframe.rdb.sharding.merger.ResultSetFactory.getResultSet(ResultSetFactory.java:66)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingStatement.executeQuery(ShardingStatement.java:99)
	at org.springframework.jdbc.core.JdbcTemplate$1QueryStatementCallback.doInStatement(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:402)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:468)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:478)
	at org.springframework.jdbc.core.JdbcTemplate.queryForList(JdbcTemplate.java:518)
	at test.Main.main(Main.java:156)

**Comment by terrymanu** [comment]
请问使用的哪个版本

**Comment by hanahmily** [comment]
这应该是一个比较pipeline改造之前的老版本，当时对于空ResultSet列表没有任何校验。请使用最新版本，已经修复了这个问题

**Comment by chenhz2284** [comment]
bm出错的版本是1.1.0
