### ISSUE TITLE
select count(*)失败出错

### ISSUE THREAD

**Issue by frankfanfan** [dangdangdotcom/sharding-jdbc#154]
我使用的是1.3.2版本，执行select count(*)出错。请问是不支持，还是什么原因？
DEBUG parser.SQLParserFactory - Logic SQL: select count(*) from t_user
DEBUG parser.SQLParseEngine - Parsed SQL result: SQLParsedResult(routeContext=RouteContext(tables=[Table(name=t_user, alias=Optional.absent())], sqlStatementType=null, sqlBuilder=null), conditionContexts=[ConditionContext(conditions={})], mergeContext=MergeContext(orderByColumns=[], groupByColumns=[], aggregationColumns=[AggregationColumn(expression=COUNT(*), aggregationType=COUNT, alias=Optional.absent(), option=Optional.absent(), derivedColumns=[], columnIndex=1)], limit=null))
DEBUG parser.SQLParseEngine - Parsed SQL: SELECT COUNT(*) FROM [Token(t_user)]
DEBUG router.SQLRouteEngine - final route result:[SQLExecutionUnit(dataSource=sharding_0, sql=SELECT COUNT(*) FROM t_user_0, sqlBuilder=SELECT COUNT(*) FROM [Token(t_user_0)]), SQLExecutionUnit(dataSource=sharding_0, sql=SELECT COUNT(*) FROM t_user_1, sqlBuilder=SELECT COUNT(*) FROM [Token(t_user_1)]), SQLExecutionUnit(dataSource=sharding_0, sql=SELECT COUNT(*) FROM t_user_2, sqlBuilder=SELECT COUNT(*) FROM [Token(t_user_2)])]
DEBUG router.SQLRouteEngine - merge context:MergeContext(orderByColumns=[], groupByColumns=[], aggregationColumns=[AggregationColumn(expression=COUNT(*), aggregationType=COUNT, alias=Optional.absent(), option=Optional.absent(), derivedColumns=[], columnIndex=1)], limit=null)
ERROR executor.ExecutorEngine - Concurrent execute result error {}
com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: java.sql.SQLException: Error
	at com.dangdang.ddframe.rdb.sharding.executor.ExecutorExceptionHandler.handleException(ExecutorExceptionHandler.java:61)
	at com.dangdang.ddframe.rdb.sharding.executor.PreparedStatementExecutor.executeInternal(PreparedStatementExecutor.java:188)
	at com.dangdang.ddframe.rdb.sharding.executor.PreparedStatementExecutor.access$200(PreparedStatementExecutor.java:46)
	at com.dangdang.ddframe.rdb.sharding.executor.PreparedStatementExecutor$4.execute(PreparedStatementExecutor.java:170)
	at com.dangdang.ddframe.rdb.sharding.executor.PreparedStatementExecutor$4.execute(PreparedStatementExecutor.java:166)
	at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine$1.call(ExecutorEngine.java:109)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Error

**Comment by hanahmily** [comment]
日志的第一句是传入的sql，count()你没写中间的*，应该导致底层数据库报错了吧。
