### ISSUE TITLE
spring boot mybatis 集成sharding jdbc

### ISSUE THREAD

**Issue by InvinciblePistachios** [dangdangdotcom/sharding-jdbc#170]
Cannot resolve reference to bean 'shardingDataSource' while setting bean property 'dataSource';

没有办法创建数据源。

**Comment by hanahmily** [comment]
请将使用的版本，配置文件，日志等详细信息提供出来

**Comment by InvinciblePistachios** [comment]
spring boot 1.4  +mybatis 3.x + duid + sharding jdbc 1.3,3  ,

还想请问一下，如果就一个数据源，只是分表怎么配置，看教程基本都是多个数据源的！

配置如下:

 
    <rdb:strategy id="tableShardingStrategyOne" sharding-columns="id" algorithm-class="com.tianhui.survey.algorithm.SingleKeyModuloTableShardingAlgorithm"/>
    
    
     <rdb:data-source id="shardingDataSource">
       <rdb:sharding-rule data-sources="defaultDatasource" >
            <rdb:table-rules>
                <rdb:table-rule logic-table="xxxxx" /> 
            </rdb:table-rules>
        </rdb:sharding-rule> 
    </rdb:data-source>


报错信息如下:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sqlSessionFactory' defined in class path resource [sharding-applicationContext.xml]: Cannot resolve reference to bean 'shardingDataSource' while setting bean property 'dataSource'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1481)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.event.AbstractApplicationEventMulticaster.retrieveApplicationListeners(AbstractApplicationEventMulticaster.java:228)
	at org.springframework.context.event.AbstractApplicationEventMulticaster.getApplicationListeners(AbstractApplicationEventMulticaster.java:185)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:382)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:336)
	at org.springframework.boot.context.event.EventPublishingRunListener.finished(EventPublishingRunListener.java:93)
	at org.springframework.boot.SpringApplicationRunListeners.callFinishedListener(SpringApplicationRunListeners.java:79)
	at org.springframework.boot.SpringApplicationRunListeners.finished(SpringApplicationRunListeners.java:72)
	at org.springframework.boot.SpringApplication.handleRunFailure(SpringApplication.java:810)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174)
	at com.tianhui.SurveyApp.main(SurveyApp.java:23)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shardingDataSource': BeanPostProcessor before instantiation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:478)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:351)
	... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration': Initialization of bean failed; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.aop.framework.autoproxy.BeanFactoryAdvisorRetrievalHelper.findAdvisorBeans(BeanFactoryAdvisorRetrievalHelper.java:92)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findCandidateAdvisors(AbstractAdvisorAutoProxyCreator.java:101)
	at org.springframework.aop.aspectj.annotation.AnnotationAwareAspectJAutoProxyCreator.findCandidateAdvisors(AnnotationAwareAspectJAutoProxyCreator.java:85)
	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.shouldSkip(AspectJAwareAdvisorAutoProxyCreator.java:103)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessBeforeInstantiation(AbstractAutoProxyCreator.java:249)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:988)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.resolveBeforeInstantiation(AbstractAutowireCapableBeanFactory.java:959)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:472)
	... 32 common frames omitted
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'org.springframework.context.annotation.ConfigurationClassPostProcessor.importRegistry' is defined
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:702)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1180)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:284)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor$ImportAwareBeanPostProcessor.postProcessBeforeInitialization(ConfigurationClassPostProcessor.java:439)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	... 54 common frames omitted
2016-11-08 09:50:46 [restartedMain] ERROR o.s.b.diagnostics.LoggingFailureAnalysisReporter [LoggingFailureAnalysisReporter.java : 42] - 

***************************
APPLICATION FAILED TO START
***************************

Description:

There is a circular dependency between 9 beans in the application context:

**Comment by hanahmily** [comment]
从问题上看你这段配置没有生效 数据源没有生成。首先检查一下spring环境需要引入该依赖
```xml
<dependency>
    <groupId>com.dangdang</groupId>
    <artifactId>sharding-jdbc-config-spring</artifactId>
    <version>1.3.3</version>
</dependency>
```

同时参照[spring配置文档](http://dangdangdotcom.github.io/sharding-jdbc/post/configuration/)中描述进行配置，同时你也可以参考ShardingJDBC集成MyBatis的例子

另外，如果不分库。可以只配置一个底层数据源就可以了，具体文档中给的例子是分库和分表都有的。你仔细看一下

**Comment by InvinciblePistachios** [comment]
感谢您的回复，pom.xml依赖，是添加好的，还是不行。

**Comment by hanahmily** [comment]
如果方便的话，可以把所有的配置文件上传一下。再帮你定位一下问题。

**Comment by InvinciblePistachios** [comment]
1 相应配置pom.xml 这些都引入了。 
<sharding-jdbc.version>1.3.3</sharding-jdbc.version>   
 <dependency>
           <groupId>com.dangdang</groupId>
           <artifactId>sharding-jdbc-core</artifactId>
           <version>${sharding-jdbc.version}</version>
        </dependency>
        <dependency>
           <groupId>com.dangdang</groupId>
           <artifactId>sharding-jdbc-config-spring</artifactId>
           <version>${sharding-jdbc.version}</version>
        </dependency>
        <dependency>
           <groupId>com.dangdang</groupId>
           <artifactId>sharding-jdbc-transaction-storage</artifactId>
           <version>${sharding-jdbc.version}</version>
        </dependency>
        <dependency>
           <groupId>com.dangdang</groupId>
           <artifactId>sharding-jdbc-config-yaml</artifactId>
           <version>${sharding-jdbc.version}</version>
        </dependency>
2 spring boot 的配置文件:

#AppName
spring.application.name=test
#ServerPort
server.port=9990
#DataSource
jdbc.datasource.driverClassName=com.mysql.jdbc.Driver
jdbc.datasource.url=jdbc:mysql://192.168.1.11:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
jdbc.datasource.username=root
jdbc.datasource.password=123456
#Logging
logging.config=classpath:logback.xml
logging.path=/var/logs/test/
#logging.file=cat-wechat.log
#logging.level.org.springframework.web=DEBUG
#logging.level.org.hibernate=ERROR
#Server Configuration
server.tomcat.uri-encoding=UTF-8
server.tomcat.max-threads=2000
server.error.path=/error

3. applicationContext.xml配置 ：
<?xml version="1.0" encoding="UTF-8" ?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
       xmlns:p="http://www.springframework.org/schema/p"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:aop="http://www.springframework.org/schema/aop"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:rdb="http://www.dangdang.com/schema/ddframe/rdb"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.springframework.org/schema/aop 
    http://www.springframework.org/schema/aop/spring-aop.xsd
    http://www.springframework.org/schema/context 
    http://www.springframework.org/schema/context/spring-context.xsd
    http://www.springframework.org/schema/tx
    http://www.springframework.org/schema/tx/spring-tx.xsd
    http://www.dangdang.com/schema/ddframe/rdb 
    http://www.dangdang.com/schema/ddframe/rdb/rdb.xsd">
    
    <bean id="parentDataSource"  class="com.alibaba.druid.pool.DruidDataSource"  init-method="init" destroy-method="close" abstract="true">
        
        <property name="initialSize" value="5" />
        
        <property name="maxActive" value="100" />
        
        <property name="minIdle" value="5" />
        
        <property name="maxWait" value="7000" />
        <property name="validationQuery" value="SELECT 1" />
        <property name="testOnBorrow" value="true" />
        <property name="testOnReturn" value="false" />
        <property name="testWhileIdle" value="true" />
        
        <property name="timeBetweenEvictionRunsMillis" value="60000" />
        
        <property name="minEvictableIdleTimeMillis" value="25200000" />
        <property name="removeAbandoned" value="true" />
        <property name="removeAbandonedTimeout" value="180" />
        
        <property name="logAbandoned" value="true" />
        
        <property name="useGlobalDataSourceStat" value="true" />
        
        <property name="filters" value="mergeStat" />
        
        <property name="connectionProperties" value="druid.stat.mergeSql=true;druid.stat.slowSqlMillis=10000" />
    </bean>
    
    
    <bean name="defaultDatasource" parent="parentDataSource">
        <property name="driverClassName" value="${jdbc.datasource.driverClassName}"></property>
        <property name="url" value="${jdbc.datasource.url}" />
        <property name="username" value="${jdbc.datasource.username}"/>
        <property name="password" value="${jdbc.datasource.password}" />
    </bean>
    
     <rdb:strategy id="tableShardingStrategyOne" sharding-columns="id" algorithm-class="com.test.test.algorithm.SingleKeyModuloTableShardingAlgorithm"/> 
    
    
      <rdb:data-source id="shardingDataSource">
       <rdb:sharding-rule data-sources="defaultDatasource" >
            <rdb:table-rules>
                <rdb:table-rule logic-table="samples" /> 
            </rdb:table-rules>
        </rdb:sharding-rule> 
    </rdb:data-source>
    
    <bean id="sqlSessionFactory" class="org.mybatis.spring.SqlSessionFactoryBean">
        <property name="dataSource" ref="shardingDataSource" />
        <property name="mapperLocations" value="classpath:mybatis/com/test/**/*.xml" />
    </bean>	   
    
    
    <bean class="org.mybatis.spring.mapper.MapperScannerConfigurer">
        <property name="sqlSessionFactoryBeanName" value="sqlSessionFactory" />
        <property name="basePackage" value="com.test.**.dao"/>
    </bean>

    <bean id="sqlSessionTemplate" class="org.mybatis.spring.SqlSessionTemplate">
        <constructor-arg ref="sqlSessionFactory"/>
    </bean>

    <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
      <property name="dataSource" ref="shardingDataSource" />  
    </bean>
    <aop:aspectj-autoproxy expose-proxy="true" proxy-target-class="true" />

    <tx:advice id="txAdvice" transaction-manager="transactionManager" >
        <tx:attributes>
            <tx:method name="submit*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="clear*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="create*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="activate*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="save*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="insert*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="add*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="update*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="delete*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="remove*" propagation="REQUIRED" rollback-for="Exception" />
            <tx:method name="execute*" propagation="REQUIRED" rollback-for="Exception" />
            
            <tx:method name="get*" propagation="SUPPORTS" rollback-for="Exception" />
            <tx:method name="find*" propagation="SUPPORTS" rollback-for="Exception" />
            <tx:method name="load*" propagation="SUPPORTS" rollback-for="Exception" />
            <tx:method name="search*" propagation="SUPPORTS" rollback-for="Exception" />
            
            <tx:method name="*" propagation="SUPPORTS" rollback-for="Exception"/>
        </tx:attributes>
    </tx:advice>
    
    <aop:config proxy-target-class="true" expose-proxy="true">
        <aop:pointcut id="transactionPointcut" expression="execution(* com.test.*.service..*.*(..)) || execution(* com.test.*.facade..*.*(..))" />
        <aop:advisor order="200" pointcut-ref="transactionPointcut" advice-ref="txAdvice"/>
    </aop:config>

**Comment by InvinciblePistachios** [comment]
pom 依赖，都引入了，下面两个附件，一个是spring boot 配置，一个是单独配置mybatis的配置文件。
[application-dev.txt](https://github.com/dangdangdotcom/sharding-jdbc/files/582874/application-dev.txt)
[applicationContext.txt](https://github.com/dangdangdotcom/sharding-jdbc/files/582875/applicationContext.txt)

**Comment by hanahmily** [comment]
下面这段配置的有问题：
```xml
 <rdb:data-source id="shardingDataSource">
       <rdb:sharding-rule data-sources="datasource_01" >
            <rdb:table-rules>
                <rdb:table-rule logic-table="samples" /> 
            </rdb:table-rules>
        </rdb:sharding-rule> 
    </rdb:data-source>

```

`datasource_01 `应该是一个bean的id，从你配置的上下文看应该配置为`defaultDatasource`

**Comment by hanahmily** [comment]
关闭 如有问题请发送邮件组询问
