### ISSUE TITLE
请问如何解决这个问题??SELECT LAST_INSERT_ID()  NullPointerException

### ISSUE THREAD

**Issue by QingHui653** [dangdangdotcom/sharding-jdbc#185]
不知道发生了什么,在完成插入后,调用了一次SELECT LAST_INSERT_ID() ,但预编译发生错误,没传入任何参数..
![image](https://cloud.githubusercontent.com/assets/15207108/20468304/6d625b9e-afd0-11e6-9d15-2db55d2dc8cb.png)

-------------------------------日志代理开始--------------------------------------------------
----------------进入的方法为 --- execution(Object newb.c.controller.ApiController.shardingTest())
----------------传入的参数为---[]
----------------开始时间---2016-11-21 09:47:56
09:47:58 [DEBUG]-[org.apache.ibatis.logging.jdbc.BaseJdbcLogger:145] - ==>  Preparing: INSERT INTO t_order ( order_id,user_id,STATUS ) VALUES( ?,?,? ) 
09:47:58 [DEBUG]-[org.apache.ibatis.logging.jdbc.BaseJdbcLogger:145] - ==> Parameters: 1(Integer), 1(Integer), 第一条数据(String)
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.parser.SQLParserFactory:62] - Logic SQL: INSERT INTO t_order  ( order_id,user_id,STATUS ) VALUES( ?,?,? ), [1, 1, 第一条数据]
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.parser.SQLParseEngine:72] - Parsed SQL result: SQLParsedResult(routeContext=RouteContext(tables=[Table(name=t_order, alias=Optional.absent())], sqlStatementType=null, sqlBuilder=null), conditionContexts=[ConditionContext(conditions={Condition.Column(columnName=order_id, tableName=t_order)=Condition(column=Condition.Column(columnName=order_id, tableName=t_order), operator==, values=[1], valueIndices=[0]), Condition.Column(columnName=user_id, tableName=t_order)=Condition(column=Condition.Column(columnName=user_id, tableName=t_order), operator==, values=[1], valueIndices=[1])})], mergeContext=MergeContext(orderByColumns=[], groupByColumns=[], aggregationColumns=[], limit=null))
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.parser.SQLParseEngine:73] - Parsed SQL: INSERT INTO [Token(t_order)] (order_id, user_id, STATUS) VALUES (?, ?, ?)
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.router.single.SingleTableRouter:169] - Before database sharding t_order routes db names: [ds_0, ds_1] sharding columns: [user_id] sharding values: [ShardingValue(logicTableName=t_order, columnName=user_id, value=1, values=[], valueRange=null)]
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.router.single.SingleTableRouter:173] - After database sharding t_order result: [ds_1]
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.router.single.SingleTableRouter:169] - Before table sharding t_order routes db names: [DataNode(dataSourceName=ds_0, tableName=t_order_0), DataNode(dataSourceName=ds_1, tableName=t_order_0), DataNode(dataSourceName=ds_0, tableName=t_order_1), DataNode(dataSourceName=ds_1, tableName=t_order_1)] sharding columns: [order_id] sharding values: [ShardingValue(logicTableName=t_order, columnName=order_id, value=1, values=[], valueRange=null)]
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.router.single.SingleTableRouter:173] - After table sharding t_order result: [t_order_1]
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine:107] - final route result is 1 target
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine:109] - ds_1:INSERT INTO t_order_1 (order_id, user_id, STATUS) VALUES (?, ?, ?) [1, 1, 第一条数据]
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine:111] - merge context:MergeContext(orderByColumns=[], groupByColumns=[], aggregationColumns=[], limit=null)
09:47:58 [DEBUG]-[org.apache.ibatis.logging.jdbc.BaseJdbcLogger:145] - <==    Updates: 1
09:47:58 [DEBUG]-[org.apache.ibatis.logging.jdbc.BaseJdbcLogger:145] - ==>  Executing: SELECT LAST_INSERT_ID() 
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.parser.SQLParserFactory:62] - Logic SQL: SELECT LAST_INSERT_ID(), []
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.parser.SQLParseEngine:72] - Parsed SQL result: SQLParsedResult(routeContext=RouteContext(tables=[], sqlStatementType=null, sqlBuilder=null), conditionContexts=[ConditionContext(conditions={})], mergeContext=MergeContext(orderByColumns=[], groupByColumns=[], aggregationColumns=[], limit=null))
09:47:58 [DEBUG]-[com.dangdang.ddframe.rdb.sharding.parser.SQLParseEngine:73] - Parsed SQL: SELECT LAST_INSERT_ID()
----------------结束时间---2016-11-21 09:47:58
-------------------------------日志代理结束--------------------------------------------------
---3--------进入后置拦截器,在渲染视图后拦截,只要用于资源清理-----------------
十一月 21, 2016 9:47:58 上午 org.apache.catalina.core.StandardWrapperValve invoke
严重: Servlet.service() for servlet [rest] in context with path [/AnewB] threw exception [Request processing failed; nested exception is org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error selecting key or setting result to parameter object. Cause: java.lang.NullPointerException] with root cause
java.lang.NullPointerException
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.routeSQL(SQLRouteEngine.java:99)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.route(SQLRouteEngine.java:73)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.route(SQLRouteEngine.java:69)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingStatement.generateExecutor(ShardingStatement.java:190)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingStatement.execute(ShardingStatement.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.StatementLogger.invoke(StatementLogger.java:57)
	at com.sun.proxy.$Proxy89.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.SimpleStatementHandler.query(SimpleStatementHandler.java:73)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:325)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Invocation.proceed(Invocation.java:49)
	at com.github.pagehelper.SqlUtil._processPage(SqlUtil.java:401)
	at com.github.pagehelper.SqlUtil.processPage(SqlUtil.java:374)
	at com.github.pagehelper.PageHelper.intercept(PageHelper.java:255)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy86.query(Unknown Source)
	at org.apache.ibatis.executor.keygen.SelectKeyGenerator.processGeneratedKeys(SelectKeyGenerator.java:68)
	at org.apache.ibatis.executor.keygen.SelectKeyGenerator.processAfter(SelectKeyGenerator.java:54)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:50)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy86.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434)
	at com.sun.proxy.$Proxy27.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:279)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:56)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:53)
	at com.sun.proxy.$Proxy38.insert(Unknown Source)
	at newb.c.service.impl.BaseServiceImpl.save(BaseServiceImpl.java:56)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
	at com.sun.proxy.$Proxy39.save(Unknown Source)
	at newb.c.controller.ApiController.shardingTest(ApiController.java:240)
	at newb.c.controller.ApiController$$FastClassBySpringCGLIB$$756783b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:720)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:655)
	at newb.c.controller.ApiController$$EnhancerBySpringCGLIB$$5b7bced0.shardingTest(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccesso
rImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:123)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:528)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1100)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:687)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
09:48:11 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=Parse SQL, count=2, min=16.139983, max=358.780078, mean=143.49375955243784, stddev=165.5823834058678, median=16.139983, p75=358.780078, p95=358.780078, p98=358.780078, p99=358.780078, p999=358.780078, mean_rate=0.0030328467491876664, m1=4.511551563772396E-6, m5=0.02333732895828166, m15=0.0976938360361154, rate_unit=events/second, duration_unit=milliseconds
09:48:11 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=Route SQL, count=1, min=31971.200595, max=31971.200595, mean=31971.200595, stddev=0.0, median=31971.200595, p75=31971.200595, p95=31971.200595, p98=31971.200595, p99=31971.200595, p999=31971.200595, mean_rate=0.001517318437690278, m1=5.201985729989746E-7, m5=4.1852626899211787E-4, m15=5.563793879495142E-4, rate_unit=events/second, duration_unit=milliseconds
09:48:11 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=ShardingConnection-getConnection-ds_1, count=1, min=5.3757839999999995, max=5.3757839999999995, mean=5.3757839999999995, stddev=0.0, median=5.3757839999999995, p75=5.3757839999999995, p95=5.3757839999999995, p98=5.3757839999999995, p99=5.3757839999999995, p999=5.3757839999999995, mean_rate=0.0015947044841396812, m1=6.506094234534289E-6, m5=0.025321420557816735, m15=0.10042673710780453, rate_unit=events/second, duration_unit=milliseconds
09:48:11 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=ShardingPreparedStatement-execute, count=2, min=37.109409, max=37.322182, mean=37.2157955, stddev=0.1063865, median=37.322182, p75=37.322182, p95=37.322182, p98=37.322182, p99=37.322182, p999=37.322182, mean_rate=0.0031896079690239437, m1=1.3012188469068578E-5, m5=0.05064284111563347, m15=0.20085347421560906, rate_unit=events/second, duration_unit=milliseconds
09:48:19 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=Parse SQL, count=2, min=7.758925, max=9.258996, mean=8.801919370084871, stddev=0.690455177183027, median=9.258996, p75=9.258996, p95=9.258996, p98=9.258996, p99=9.258996, p999=9.258996, mean_rate=0.00833359425039129, m1=0.005123624982947121, m5=0.09472601576626503, m15=0.15580440023488007, rate_unit=events/second, duration_unit=milliseconds
09:48:19 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=Route SQL, count=1, min=33159.587512, max=33159.587512, mean=33159.587512, stddev=0.0, median=33159.587512, p75=33159.587512, p95=33159.587512, p98=33159.587512, p99=33159.587512, p999=33159.587512, mean_rate=0.004166925124347067, m1=5.704670041178395E-4, m5=0.0016972077121404608, m15=8.87241384064672E-4, rate_unit=events/second, duration_unit=milliseconds
09:48:19 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=ShardingConnection-getConnection-ds_1, count=1, min=1.70416, max=1.70416, mean=1.70416, stddev=0.0, median=1.70416, p75=1.70416, p95=1.70416, p98=1.70416, p99=1.70416, p999=1.70416, mean_rate=0.00483510688743957, m1=0.007134798669450493, m5=0.10268342380651839, m15=0.16014748058336156, rate_unit=events/second, duration_unit=milliseconds
09:48:19 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=ShardingPreparedStatement-execute, count=2, min=16.147879, max=16.297491, mean=16.222685, stddev=0.074806, median=16.297491, p75=16.297491, p95=16.297491, p98=16.297491, p99=16.297491, p999=16.297491, mean_rate=0.009670302389718019, m1=0.014269597338900986, m5=0.20536684761303678, m15=0.3202949611667231, rate_unit=events/second, duration_unit=milliseconds
09:48:20 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=Parse SQL, count=2, min=1.945357, max=2.268267, mean=2.1068119999999997, stddev=0.161455, median=2.268267, p75=2.268267, p95=2.268267, p98=2.268267, p99=2.268267, p999=2.268267, mean_rate=0.003333361755992352, m1=2.1453471907312295E-5, m5=0.055968995209723794, m15=0.20766142552374287, rate_unit=events/second, duration_unit=milliseconds
09:48:20 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=Route SQL, count=1, min=3.435165, max=3.435165, mean=3.435165, stddev=0.0, median=3.435165, p75=3.435165, p95=3.435165, p98=3.435165, p99=3.435165, p999=3.435165, mean_rate=0.0016666865922021021, m1=1.0726735953656148E-5, m5=0.027984497604861897, m15=0.10383071276187143, rate_unit=events/second, duration_unit=milliseconds
09:48:20 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=ShardingConnection-getConnection-ds_1, count=1, min=0.7456929999999999, max=0.7456929999999999, mean=0.7456929999999999, stddev=0.0, median=0.7456929999999999, p75=0.7456929999999999, p95=0.7456929999999999, p98=0.7456929999999999, p99=0.7456929999999999, p999=0.7456929999999999, mean_rate=0.001666704837132504, m1=1.0726735953656148E-5, m5=0.027984497604861897, m15=0.10383071276187143, rate_unit=events/second, duration_unit=milliseconds
09:48:20 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=ShardingPreparedStatement-execute, count=2, min=2.9105339999999997, max=2.945667, mean=2.9281004999999998, stddev=0.0175665, median=2.945667, p75=2.945667, p95=2.945667, p98=2.945667, p99=2.945667, p999=2.945667, mean_rate=0.0033334234826324473, m1=2.1453471907312295E-5, m5=0.055968995209723794, m15=0.20766142552374287, rate_unit=events/second, duration_unit=milliseconds
09:48:28 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=Parse SQL, count=2, min=5.674614, max=9.655331, mean=7.664972499999999, stddev=1.9903585, median=9.655331, p75=9.655331, p95=9.655331, p98=9.655331, p99=9.655331, p999=9.655331, mean_rate=0.0666863822110388, m1=0.2866125242295158, m5=0.37420279401264706, m15=0.39120914899384024, rate_unit=events/second, duration_unit=milliseconds
09:48:28 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=Route SQL, count=1, min=5.166563, max=5.166563, mean=5.166563, stddev=0.0, median=5.166563, p75=5.166563, p95=5.166563, p98=5.166563, p99=5.166563, p999=5.166563, mean_rate=0.03335381267771427, m1=0.1433062621147579, m5=0.18710139700632353, m15=0.19560457449692012, rate_unit=events/second, duration_unit=milliseconds
09:48:28 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=ShardingConnection-getConnection-ds_1, count=1, min=1.675738, max=1.675738, mean=1.675738, stddev=0.0, median=1.675738, p75=1.675738, p95=1.675738, p98=1.675738, p99=1.675738, p999=1.675738, mean_rate=0.033362122712282324, m1=0.1433062621147579, m5=0.18710139700632353, m15=0.19560457449692012, rate_unit=events/second, duration_unit=milliseconds
09:48:28 [DEBUG]-[com.codahale.metrics.Slf4jReporter$DebugLoggerProxy:279] - type=TIMER, name=ShardingPreparedStatement-execute, count=2, min=26.988267, max=27.060506999999998, mean=27.024386999999997, stddev=0.03612, median=27.060506999999998, p75=27.060506999999998, p95=27.060506999999998, p98=27.060506999999998, p99=27.060506999999998, p999=27.060506999999998, mean_rate=0.06673684030297508, m1=0.2866125242295158, m5=0.37420279401264706, m15=0.39120914899384024, rate_unit=events/second, duration_unit=milliseconds

**Comment by QingHui653** [comment]
![image](https://cloud.githubusercontent.com/assets/15207108/20468298/57db66da-afd0-11e6-9dda-d834d3dfcccf.png)

**Comment by hanahmily** [comment]
目前还不支持“SELECT LAST_INSERT_ID()”语法来返回生成的主键，请看[Mybatis的例子](https://github.com/dangdangdotcom/sharding-jdbc/tree/master/sharding-jdbc-example/sharding-jdbc-example-mybatis)来返回生成的主键。
