### ISSUE TITLE
并发执行sql时报了IndexOutOfBoundsException

### ISSUE THREAD

**Issue by ben1247** [dangdangdotcom/sharding-jdbc#206]
1. 现象：local环境不报错，线上环境执行10次，平均6次成功，4次失败
2. 使用sjdbc+druid+mybatis
3. mybatis.xml 代码：
<select id="statFansRegion"
            parameterType="com.shuyun.wxcrm.fans.model.FansStatSearch"
            resultType="com.shuyun.wxcrm.fans.model.FansRegionStat">
        SELECT
        country,
        province,
        count(openid)AS count
        FROM
        wechat_user_info
        WHERE
        tenant_id = #{tenantId}
        AND wechat_public_number = #{wechatPublicNumber}
        AND subscribe = 1
        AND country is not null
        AND province is not NULL
        AND country != ''
        and province != ''
        GROUP BY country,province
        order BY count DESC
        <if test="pageNum != null">
            LIMIT #{offset} , #{pageSize}
        </if>
    </select>

3. 报错信息：

Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### SQL: SELECT         
            country, province, count(openid)AS count         
        FROM         
            wechat_user_info         
        WHERE         
            tenant_id = ?         
            AND wechat_public_number = ?         
            AND subscribe = 1         
            AND country is not null         
            AND province is not NULL         
            AND country != ''         
            and province != '' 
            GROUP BY country,province         
            order BY count DESC                       
            LIMIT ? , ?
### Cause: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
    at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:150) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:141) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_91]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_91]
    at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:434) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    ... 67 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
    at java.util.ArrayList.rangeCheck(Unknown Source) ~[na:1.8.0_91]
    at java.util.ArrayList.get(Unknown Source) ~[na:1.8.0_91]
    at com.dangdang.ddframe.rdb.sharding.jdbc.util.ParameterList.set(ParameterList.java:82) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at com.dangdang.ddframe.rdb.sharding.parser.result.merger.Limit.replaceParameters(Limit.java:71) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.routeSQL(SQLRouteEngine.java:105) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at com.dangdang.ddframe.rdb.sharding.router.PreparedSQLRouter.route(PreparedSQLRouter.java:56) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeSQL(ShardingPreparedStatement.java:162) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:112) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:63) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:83) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:148) ~[wxcrm-server-fans-1.0-SNAPSHOT.jar:na]
    ... 73 common frames omitted

**Comment by hanahmily** [comment]
请发送debug级别日志到邮件组，issue里面只能发送一些确定的bug

**Comment by dzxiang** [comment]
我也碰到这个问题了，偶尔会出现，第二次操作又没问题。

**Comment by dzxiang** [comment]
### The error occurred while setting parameters
### SQL: select ID, TP_ID from t_member WHERE (  APP_ID = ?   and GROUP_ID = ? )  limit ?,?
### Cause: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:122)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:113)
    at sun.reflect.GeneratedMethodAccessor333.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:386)
    ... 24 common frames omitted
Caused by: java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
    at java.util.ArrayList.rangeCheck(ArrayList.java:653)
    at java.util.ArrayList.get(ArrayList.java:429)
    at com.dangdang.ddframe.rdb.sharding.jdbc.util.ParameterList.set(ParameterList.java:82)
    at com.dangdang.ddframe.rdb.sharding.parser.result.merger.Limit.replaceParameters(Limit.java:71)
    at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.routeSQL(SQLRouteEngine.java:105)
    at com.dangdang.ddframe.rdb.sharding.router.PreparedSQLRouter.route(PreparedSQLRouter.java:56)
    at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeSQL(ShardingPreparedStatement.java:162)
    at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:112)
    at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:62)
    at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:78)
    at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:62)
    at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:303)
    at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:154)
    at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:134)
    at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:120)
    ... 29 common frames omitted

=========
sjdbc-1.3.3+mybatis+springmvc出现这个异常，不是每次都能重现。
 
用sjdbc-1.3.2的时候没有出过这个异常，sjdbc-1.4.0和sjdbc-1.3.3均出现。

**Comment by dzxiang** [comment]
@ben1247 ，可以确信这是一个BUG,能否提交一个DEBUG级别的日志，我这边本地测试没出现过，生产环境有出现，但修改日志级别要等下一次更新。

**Comment by ben1247** [comment]
@dzxiang 最新版本的1.4.1 涛哥已经修复了该问题，我这边已经没有这个错了

**Comment by ijiaojian** [comment]
谁能描述一下这个问题产生的原因么？  我也遇到了，更换了版本后问题没有了。

**Comment by liyong7514** [comment]
请描述一下 这个问题，我也遇到了。

**Comment by acseed** [comment]
> @ben1247 ，可以确信这是一个BUG,能否提交一个DEBUG级别的日志，我这边本地测试没出现过，生产环境有出现，但修改日志级别要等下一次更新。

这个循环删除有问题， 我这边在有subQuery的时候出现， 
remove之后下标就变了， 还拿之前的下标remove就出问题了

代码位置：SelectStatement.resetLimitTokens
for (int each : toBeRemovedIndexes) {
            sqlTokens.remove(each);
 }

**Comment by acseed** [comment]
这个循环删除有问题， 我这边在有subQuery的时候出现，
remove之后下标就变了， 还拿之前的下标remove就出问题了

代码位置：SelectStatement.resetLimitTokens
for (int each : toBeRemovedIndexes) {
sqlTokens.remove(each);
}
