### ISSUE TITLE
只是使用分表，在保存行时，出现java.sql.SQLException: Can't call commit when autocommit=true

### ISSUE THREAD

**Issue by EonianGlutton** [dangdangdotcom/sharding-jdbc#254]
使用版本：1.4.1，连接池：druid 1.0.12
只是使用了分表，在开发和测试环境下，一切正常。。。
在生产环境(原来单表数据在一亿以上)，出现这个异常：
Caused by: java.sql.SQLException: Can't call commit when autocommit=true
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:880) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:876) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.mysql.jdbc.ConnectionImpl.commit(ConnectionImpl.java:1604) ~[mysql-connector-java-5.1.36.jar:5.1.36]
	at com.alibaba.druid.filter.FilterChainImpl.connection_commit(FilterChainImpl.java:180) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.filter.stat.StatFilter.connection_commit(StatFilter.java:260) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.filter.FilterChainImpl.connection_commit(FilterChainImpl.java:176) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.proxy.jdbc.ConnectionProxyImpl.commit(ConnectionProxyImpl.java:123) ~[druid-1.0.12.jar:1.0.12]
	at com.alibaba.druid.pool.DruidPooledConnection.commit(DruidPooledConnection.java:718) ~[druid-1.0.12.jar:1.0.12]
	at com.dangdang.ddframe.rdb.sharding.jdbc.adapter.AbstractConnectionAdapter.commit(AbstractConnectionAdapter.java:68) ~[sharding-jdbc-core-1.4.1.jar:na]
	at org.springframework.jdbc.datasource.DataSourceTransactionManager.doCommit(DataSourceTransactionManager.java:268) ~[spring-jdbc-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	... 39 common frames omitted

其他的业务并没有sharding，配置事务的时候，需要注意点儿什么呢？
多谢。

**Comment by terrymanu** [comment]
有2个建议可以试一下：
1. 可以用1.5.0.M1试一下
2. 是否业务代码中设置了autocommit，导致事务失败。这需要了解一下这个程序的dao框架是怎么设置的，是否是spring的transaction设置有问题？

**Comment by terrymanu** [comment]
无法重现且长时间无反馈，先关闭了。有需要请再开启。
