### ISSUE TITLE
插入insert语句查找不到分片值

### ISSUE THREAD

**Issue by WZQ1993** [dangdangdotcom/sharding-jdbc#264]
##在执行插入语句的时候报错
```
Caused by: java.lang.IllegalStateException: INSERT statement should contain com.dangdang.ddframe.rdb.sharding value.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at com.dangdang.ddframe.rdb.sharding.router.strategy.ShardingStrategy.doStaticSharding(ShardingStrategy.java:57)
	at com.dangdang.ddframe.rdb.sharding.router.single.SingleTableRouter.routeDataSources(SingleTableRouter.java:106)
	at com.dangdang.ddframe.rdb.sharding.router.single.SingleTableRouter.route(SingleTableRouter.java:92)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.routeSQL(SQLRouteEngine.java:147)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.routeSQL(SQLRouteEngine.java:122)
	at com.dangdang.ddframe.rdb.sharding.router.PreparedSQLRouter.route(PreparedSQLRouter.java:66)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeSQL(ShardingPreparedStatement.java:162)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:106)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:204)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2949)
	at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3449)
	at org.hibernate.action.internal.EntityInsertAction.execute(EntityInsertAction.java:89)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:582)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:456)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:337)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:39)
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1282)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:465)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:2963)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2339)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:485)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:147)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$100(JdbcResourceLocalTransactionCoordinatorImpl.java:38)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:231)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:65)
	at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:61)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517)
	... 45 more

```

**Comment by terrymanu** [comment]
应该就是如异常所说，insert语句没有传sharding key吧？如果确实是这样请核实后关闭issue

**Comment by terrymanu** [comment]
长时间无反馈，先关闭了。
通过描述分析应该不是bug，是sharding-jdbc的正常行为。
后期有更新欢迎reopen issue再讨论。
