### ISSUE TITLE
generate-key-column 不配置 插入数据不成功

### ISSUE THREAD

**Issue by jiangyilong** [dangdangdotcom/sharding-jdbc#276]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
使用 sharding-jdbc 1.5.0.m2
在目前的使用中， 有部分表要做分表操作， 有一部分保存不变。

表结构为：
CREATE TABLE `chat_content` (
  `id` bigint(19) NOT NULL AUTO_INCREMENT,
  `content` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14775 DEFAULT CHARSET=utf8mb4;

插入语句： 
<insert id="insert" parameterType="com.yiguo.qiakr.example.jdbc.entity.ChatContent"
		useGeneratedKeys="true" keyProperty="id">
		insert into chat_content (
		content
		)
		values (
		#{content}
		)
	</insert>
现在保持不变的表 如果没有 配置：
 <rdb:table-rule logic-table="chat_content" actual-tables="chat_content">
                  <rdb:generate-key-column column-name="id"/>
            </rdb:table-rule> 
在向表里插入数据的时候，报下面错误， 个人觉得即使不配置 也可以正常：
Exception in thread "main" org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: java.lang.IllegalStateException: ResultSet has closed.
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	at com.sun.proxy.$Proxy16.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:51)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)
	at com.sun.proxy.$Proxy18.insert(Unknown Source)
	at com.yiguo.qiakr.example.jdbc.service.ChatlogService.insertContent(ChatlogService.java:109)
	at com.yiguo.qiakr.example.jdbc.service.ChatlogService$$FastClassBySpringCGLIB$$70c88c09.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:649)
	at com.yiguo.qiakr.example.jdbc.service.ChatlogService$$EnhancerBySpringCGLIB$$eeea63a3.insertContent(<generated>)
	at com.yiguo.qiakr.example.jdbc.service.ChatService.insert(ChatService.java:182)
	at com.yiguo.qiakr.example.jdbc.service.ChatService.insertBatch(ChatService.java:129)
	at com.yiguo.qiakr.example.jdbc.Main.main(Main.java:41)
Caused by: org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: java.lang.IllegalStateException: ResultSet has closed.
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:66)
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processAfter(Jdbc3KeyGenerator.java:45)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:48)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:69)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:48)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:105)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:71)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:152)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:358)
	... 13 more
Caused by: java.lang.IllegalStateException: ResultSet has closed.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.resultset.GeneratedKeysResultSet.checkState(GeneratedKeysResultSet.java:234)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.resultset.GeneratedKeysResultSet.getMetaData(GeneratedKeysResultSet.java:78)
	at org.apache.ibatis.executor.keygen.Jdbc3KeyGenerator.processBatch(Jdbc3KeyGenerator.java:55)
	... 26 more

**Comment by haocao** [comment]
Mybatis的mapper文件里面是否配置了自增主键：
<insert id="insert" useGeneratedKeys="true" keyProperty="orderId">
        INSERT INTO t_order (
          user_id, status
        )
        VALUES (
        #{userId,jdbcType=INTEGER},
        #{status,jdbcType=VARCHAR}
        )
    </insert>

可参照sharding-jdbc-example-mybatis这个demo，对比配置有没有问题，如果还是有问题，建议提供完整代码，以便调试。

**Comment by jiangyilong** [comment]
我使用了 自增主键
<insert id="insert" parameterType="com.yiguo.qiakr.example.jdbc.entity.ChatContent"
		useGeneratedKeys="true" keyProperty="id">
		insert into chat_content (
		content
		)
		values (
		#{content}
		
		)
	</insert>

我去掉了确实可以了。 但是在1.4.0版本都是支持的。这个版本能否也支持，即使写了也行。 因为现在项目上所有插入数据的地方都这么写了。

**Comment by haocao** [comment]
我们没有重现这个问题，请参照sharding-jdbc-example-mybatis里面示例代码，补充可以重现的完整测试代码代码给我们。

**Comment by terrymanu** [comment]
fixed at 1.5.0.M3
