### ISSUE TITLE
使用mysql函数会报错。

### ISSUE THREAD

**Issue by michaelzhou2016** [dangdangdotcom/sharding-jdbc#284]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?

1.5.0.M1，1.5.0.M2

### Expected behavior

使用mysql函数不报错

### Actual behavior

报错，设参数值有问题。

### Cause: java.lang.RuntimeException: Wrong number type to transfer.
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:77)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:446)
	at com.sun.proxy.$Proxy50.selectList(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.selectList(SqlSessionTemplate.java:230)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:137)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:75)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy52.getOrderInfoList(Unknown Source)
	at com.quixmart.order.service.impl.OrdOrderInfoServiceImpl.getOrderInfoList(OrdOrderInfoServiceImpl.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

### Steps to reproduce the behavior

  SQL查询语句中使用mysql函数，比如DATE_FORMAT函数。

### Please provide the reproduce example codes (such as github link) if possible.
select ooi.id , ooi.store_Id ,
        ooi.payment_type_id , ooi.order_total ,
        ooi.create_time , ooi.payment_time ,
        ooi.member_cardNo , ooi.user_tel ,
        ooi.order_node
        from ord_order_info ooi
        where ooi.store_id = #{storeID,jdbcType=BIGINT}
        <if test="saleDate != null">
            and DATE_FORMAT(ooi.create_time,'%Y-%m-%d') = DATE_FORMAT(#{saleDate,jdbcType=TIMESTAMP},'%Y-%m-%d')
        </if>

**Comment by terrymanu** [comment]
看报错信息完全是mybatis的问题？
请提供sharding-jdbc的info日志

或者提供可供重现的源码

**Comment by terrymanu** [comment]
长时间无反馈，我关闭了。
下次再提issue时请多关注，而不是没有描述清楚的情况下就不管了，谢谢合作。
