### ISSUE TITLE
程序有时候拿mysql连接失败

### ISSUE THREAD

**Issue by chinaer** [dangdangdotcom/sharding-jdbc#289]
我使用的是1.4.2 版本，我的应用是接收mq消息并处理，mq消息是偶尔推送，jstack里面有很多blocked状态，请问这是为什么？程序有时候拿mysql连接失败

"ShardingJDBC-8" #92 daemon prio=5 os_prio=0 tid=0x00002b44a8084000 nid=0x28ba waiting for monitor entry [0x00002b44a762e000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at com.mchange.v2.c3p0.impl.NewProxyConnection.maybeDirtyTransaction(NewProxyConnection.java:1348)
        - waiting to lock <0x00000000e6d28a80> (a com.mchange.v2.c3p0.impl.NewProxyConnection)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.maybeDirtyTransaction(NewProxyPreparedStatement.java:2069)
        at com.mchange.v2.c3p0.impl.NewProxyPreparedStatement.getConnection(NewProxyPreparedStatement.java:1877)
        at com.dangdang.ddframe.rdb.sharding.executor.PreparedStatementExecutor$4.execute(PreparedStatementExecutor.java:175)
        at com.dangdang.ddframe.rdb.sharding.executor.PreparedStatementExecutor$4.execute(PreparedStatementExecutor.java:171)
        at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine$1.call(ExecutorEngine.java:114)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

**Comment by terrymanu** [comment]
精力有限，我们只维护最新版本。目前1.5.0.M2已经发布，1.4.2不再维护，请升级至最新版本再尝试一下。

另外，目前的日志只是jstack，看不到获取不到连接的日志。而且重现条件也不够充分，我们无法处理。如果想继续追踪这个issue，请提供全部日志以及可供重现的代码。

**Comment by terrymanu** [comment]
长时间无反馈，我关闭了。
下次再提issue时请多关注，而不是没有描述清楚的情况下就不管了，谢谢合作。
