### ISSUE TITLE
select last_insert_id() 出现异常，如何解决？

### ISSUE THREAD

**Issue by kevingzhz** [dangdangdotcom/sharding-jdbc#298]
版本：1.5.0.M2
在使用jdbc 或者 mybatis时，需要获取最新的插入值，使用了mysql的last_insert_id() 函数，
结果报出如下异常信息：
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error selecting key or setting result to parameter object. Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]'
	at org.mybatis.spring.MyBatisExceptionTranslator.translateExceptionIfPossible(MyBatisExceptionTranslator.java:75)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:371)
	at com.sun.proxy.$Proxy90.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:240)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:51)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:52)

请问是否sharding-jdbc目前就不支持last_insert_id() 函数？

**Comment by terrymanu** [comment]
目前并未打算支持last_insert_id()

**Comment by ljjandgy** [comment]
请问现在打算支持这个功能吗？
