### ISSUE TITLE
insert报错

### ISSUE THREAD

**Issue by lanmo** [dangdangdotcom/sharding-jdbc#299]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
com.dangdang.sharding-jdbc-core.1.4.2
### Expected behavior
期望保存成功
### Actual behavior
Caused by: org.apache.ibatis.exceptions.PersistenceException: 
### Cause: java.lang.IllegalStateException: INSERT statement should contain sharding value.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:200)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	... 7 more
Caused by: java.lang.IllegalStateException: INSERT statement should contain sharding value.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:173)
	at com.dangdang.ddframe.rdb.sharding.router.strategy.ShardingStrategy.doStaticSharding(ShardingStrategy.java:56)
	at com.dangdang.ddframe.rdb.sharding.router.single.SingleTableRouter.routeTables(SingleTableRouter.java:128)
	at com.dangdang.ddframe.rdb.sharding.router.single.SingleTableRouter.route(SingleTableRouter.java:96)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.routeSQL(SQLRouteEngine.java:142)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.routeSQL(SQLRouteEngine.java:117)
	at com.dangdang.ddframe.rdb.sharding.router.PreparedSQLRouter.route(PreparedSQLRouter.java:62)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeSQL(ShardingPreparedStatement.java:162)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:115)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:46)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	... 13 more
### Steps to reproduce the behavior
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:context="http://www.springframework.org/schema/context"
       xmlns:tx="http://www.springframework.org/schema/tx"
       xmlns:rdb="http://www.dangdang.com/schema/ddframe/rdb"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
                        http://www.springframework.org/schema/beans/spring-beans.xsd
                        http://www.springframework.org/schema/context
                        http://www.springframework.org/schema/context/spring-context.xsd
                        http://www.dangdang.com/schema/ddframe/rdb
                        http://www.dangdang.com/schema/ddframe/rdb/rdb.xsd
                        http://www.springframework.org/schema/tx
                        http://www.springframework.org/schema/tx/spring-tx.xsd
                        ">
    <context:property-placeholder location="classpath:db.properties" ignore-unresolvable="true"/>

    
        
        
        
        
    

    <bean id="db0" class="com.zaxxer.hikari.HikariDataSource" destroy-method="close">
        <property name="driverClassName" value="${mysql.jdbc.db.driver}"/>
        <property name="jdbcUrl" value="${mysql.jdbc.db0.url}"/>
        <property name="username" value="${mysql.jdbc.db0.name}"/>
        <property name="password" value="${mysql.jdbc.db0.password}"/>
    </bean>

    
    <rdb:strategy id="tableStrategy" sharding-columns="user_id" algorithm-class="com.yn.sharding.jdbc.strategy.TableStrategy"/>

    <rdb:data-source id="shardingDataSource">
        <rdb:sharding-rule data-sources="db0">
            <rdb:table-rules>
                <rdb:table-rule logic-table="t_user" actual-tables="t_user_${0..9}" table-strategy="tableStrategy"/>
            </rdb:table-rules>
            
            
        </rdb:sharding-rule>
    </rdb:data-source>

    <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
        <property name="dataSource" ref="shardingDataSource" />
    </bean>
    <tx:annotation-driven transaction-manager="transactionManager" />
</beans>

mapper.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE mapper PUBLIC "-//mybatis.org//DTD Mapper 3.0//EN" "http://mybatis.org/dtd/mybatis-3-mapper.dtd" >
<mapper namespace="com.yn.sharding.jdbc.mapper.UserRepository" >
    <resultMap id="resultMap" type="com.yn.sharding.jdbc.entity.User" >
        <result column="id" property="id" />
        <result column="user_id" property="userId" />
        <result column="name" property="name" />
        <result column="password" property="password" />
        <result column="create_time" property="createTime" />
        <result column="update_time" property="updateTime" />
    </resultMap>

    <insert id="insert" parameterType="com.yn.sharding.jdbc.entity.User">
        insert into t_user (user_id) VALUES (#{userId})
        
            
                
            
            
                
            
            
                
            
            
                
            
            
                
            
        
        
        
            
                
            
            
                
            
            
                
            
            
                
            
            
                
            
        
    </insert>

    <select id="findAll" resultMap="resultMap" parameterType="long">
        select <include refid="columnsName"/> from t_user where user_id=#{userId}
    </select>

    <sql id="columnsName">
        id,user_id,name,password,create_time,update_time
    </sql>
</mapper>
有这个user_id，如果        insert into t_user (user_id) VALUES (#{userId})更换成        insert into t_user (user_id) VALUES (${userId})，就能正常使用

**Comment by terrymanu** [comment]
请提供 tableStrategy这个class。
建议升级到1.5.0.m3，然后发送过来sharding-jdbc的info执行日志，
或者直接提供可供重现、可运行的demo

**Comment by lanmo** [comment]
升级到1.5.0.M3 问题已解决，也就是以前的版本会存在这个问题是吗？

**Comment by terrymanu** [comment]
既然新版本已解决，欢迎使用新版本
