### ISSUE TITLE
在使用Sharding-jdbc时出现一个诡异bug

### ISSUE THREAD

**Issue by oopp1990** [dangdangdotcom/sharding-jdbc#348]
Please answer these questions before submitting your issue. Thanks!

### Which version of Sharding-Jdbc do you using?
Sharding-jdbc 1.5.1
### Expected behavior
使用技术：
             sharding-jdbc 1.5.1  
             mybatis 3.4.4  
             mybatis-spring 1.3.1
            pagehelper 5.0.3 

当使用配置：
mapper.identity=MYSQL
实体类 为自增id      
   @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
时，使用读写分离（仅仅使用读写分离功能） 出现以下错误
提示信息为：
==>  Executing: SELECT LAST_INSERT_ID() 
Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]'

当使用： 
mapper.identity=JDBC时， 不执行 SELECT LAST_INSERT_ID()  就不会报错， 但是期望是能够得到插入的id。 
## 是否能支持在插入时，查询最后插入的id？ 

具体错误堆栈如下
Registering transaction synchronization for SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1e225820]
JDBC Connection [com.dangdang.ddframe.rdb.sharding.jdbc.core.connection.ShardingConnection@41f4039e] will be managed by Spring
==>  Preparing: INSERT INTO shardingtest ( id,name,pwd ) VALUES( ?,?,? ) 
==> Parameters: null, zhangsan0(String), lisi0(String)
<==    Updates: 1
==>  Executing: SELECT LAST_INSERT_ID() 
Releasing transactional SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1e225820]
Transaction synchronization deregistering SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1e225820]
Transaction synchronization closing SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@1e225820]
2017-08-29 13:55:56,951 INFO (TransactionContext.java:136)- Rolled back transaction for test context [DefaultTestContext@6ea246af testClass = TestDb, testInstance = com.freemud.test.TestDb@2e4389ed, testMethod = testShardingInsert@TestDb, testException = org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error selecting key or setting result to parameter object. Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]', mergedContextConfiguration = [WebMergedContextConfiguration@16da476c testClass = TestDb, locations = '{}', classes = '{class com.freemud.test.Application, class com.freemud.test.Application}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.SpringBootTestContextCustomizer@71a794e5, org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@4df828d7, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@146044d7], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]]].
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.7 sec <<< FAILURE! - in com.freemud.test.TestDb
testShardingInsert(com.freemud.test.TestDb)  Time elapsed: 0.233 sec  <<< ERROR!
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error selecting key or setting result to parameter object. Cause: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: Cannot find table rule and default data source with logic tables: '[]'
	at com.dangdang.ddframe.rdb.sharding.routing.type.complex.ComplexRoutingEngine.route(ComplexRoutingEngine.java:81)
	at com.dangdang.ddframe.rdb.sharding.routing.router.ParsingSQLRouter.route(ParsingSQLRouter.java:123)
	at com.dangdang.ddframe.rdb.sharding.routing.router.ParsingSQLRouter.route(ParsingSQLRouter.java:89)
	at com.dangdang.ddframe.rdb.sharding.routing.StatementRoutingEngine.route(StatementRoutingEngine.java:48)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingStatement.generateExecutor(ShardingStatement.java:206)
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingStatement.execute(ShardingStatement.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.logging.jdbc.StatementLogger.invoke(StatementLogger.java:57)
	at com.sun.proxy.$Proxy88.execute(Unknown Source)
	at org.apache.ibatis.executor.statement.SimpleStatementHandler.query(SimpleStatementHandler.java:73)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.CachingExecutor.query(CachingExecutor.java:109)
	at com.github.pagehelper.PageInterceptor.intercept(PageInterceptor.java:142)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:61)
	at com.sun.proxy.$Proxy85.query(Unknown Source)
	at tk.mybatis.mapper.mapperhelper.SelectKeyGenerator.processGeneratedKeys(SelectKeyGenerator.java:69)
	at tk.mybatis.mapper.mapperhelper.SelectKeyGenerator.processAfter(SelectKeyGenerator.java:55)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:50)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.executor.CachingExecutor.update(CachingExecutor.java:76)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.ibatis.plugin.Plugin.invoke(Plugin.java:63)
	at com.sun.proxy.$Proxy85.update(Unknown Source)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:198)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.insert(DefaultSqlSession.java:185)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mybatis.spring.SqlSessionTemplate$SqlSessionInterceptor.invoke(SqlSessionTemplate.java:433)
	at com.sun.proxy.$Proxy69.insert(Unknown Source)
	at org.mybatis.spring.SqlSessionTemplate.insert(SqlSessionTemplate.java:278)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:57)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:59)
	at com.sun.proxy.$Proxy77.insert(Unknown Source)
	at com.freemud.test.TestDb.testShardingInsert(TestDb.java:54)

**Comment by oopp1990** [comment]
额， 看完源码才发现这不是bug是不支持这个操作........ 也不支持replace

**Comment by terrymanu** [comment]
不支持LAST_INSERT_ID()
