### ISSUE TITLE
读写分离事务问题

### ISSUE THREAD

**Issue by shengyue-z** [dangdangdotcom/sharding-jdbc#383]
配置读写分离（一主一从），sharding-jdbc 在执行sql前根据sqlType 判断获取主从数据源，如果我先查询用户信息（它从从库获取到了数据，然后我对这个用户的密码做更改，sharding根据sqlType又拿到了主库数据源），在这时提交事务的时候报错，大致信息是
Caused by: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: com.dangdang.ddframe.rdb.sharding.exception.ShardingJdbcException: java.sql.SQLException: Connection is read-only. Queries leading to data modification are not allowed
	at com.dangdang.ddframe.rdb.sharding.executor.threadlocal.ExecutorExceptionHandler.handleException(ExecutorExceptionHandler.java:61) ~[sharding-jdbc-core-1.5.3.jar:na]
	at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine.execute(ExecutorEngine.java:129) ~[sharding-jdbc-core-1.5.3.jar:na]
	at com.dangdang.ddframe.rdb.sharding.executor.ExecutorEngine.executePreparedStatement(ExecutorEngine.java:96) ~[sharding-jdbc-core-1.5.3.jar:na]
	at com.dangdang.ddframe.rdb.sharding.executor.type.prepared.PreparedStatementExecutor.executeUpdate(PreparedStatementExecutor.java:69) ~[sharding-jdbc-core-1.5.3.jar:na]
	at com.dangdang.ddframe.rdb.sharding.jdbc.core.statement.ShardingPreparedStatement.executeUpdate(ShardingPreparedStatement.java:129) ~[sharding-jdbc-core-1.5.3.jar:na]
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:62) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3281) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.updateOrInsert(AbstractEntityPersister.java:3183) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.persister.entity.AbstractEntityPersister.update(AbstractEntityPersister.java:3525) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.action.internal.EntityUpdateAction.execute(EntityUpdateAction.java:159) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:465) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:351) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:350) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:56) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.internal.SessionImpl.flush(SessionImpl.java:1258) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:425) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.engine.transaction.internal.jdbc.JdbcTransaction.beforeTransactionCommit(JdbcTransaction.java:101) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.engine.transaction.spi.AbstractTransactionImpl.commit(AbstractTransactionImpl.java:177) ~[hibernate-core-4.3.10.Final.jar:4.3.10.Final]
	at org.hibernate.jpa.internal.TransactionImpl.commit(TransactionImpl.java:77) ~[hibernate-entitymanager-4.3.10.Final.jar:4.3.10.Final]
	... 118 common frames omitted
比如这种场景因为是不同的数据源 应该根据当前sqlType 来重新开启新的事务（DQL read-only =true other false）
还有我不能理解 读写分离 重新开启事务效率为什么会低？

**Comment by terrymanu** [comment]
读写分离是两个库，我们目前还没有考虑过开启一般事务应该如何运行。如果想用事务，请使用分布式事务。
但是我们并不建议使用分布式事务，因此请从设计角度考虑读写分离是否真的需要ACID事务，还是使用BASE事务补偿机制来处理
