### ISSUE TITLE
向含有text字段类型的分表中插入数据时失败

### ISSUE THREAD

**Issue by dzxiang** [dangdangdotcom/sharding-jdbc#59]
# **MyBatis+MySQL，向含有text字段类型的分表中插入数据数据时失败，异常信息如下：**
Caused by: java.sql.SQLException: Invalid argument value: java.io.NotSerializableException
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:937)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:926)
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:872)
at com.mysql.jdbc.PreparedStatement.setSerializableObject(PreparedStatement.java:3887)
at com.mysql.jdbc.PreparedStatement.setObject(PreparedStatement.java:3603)
at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setObject(FilterChainImpl.java:2923)
at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setObject(FilterAdapter.java:1298)
at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setObject(FilterChainImpl.java:2920)
at com.alibaba.druid.filter.FilterAdapter.preparedStatement_setObject(FilterAdapter.java:1298)
at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_setObject(FilterChainImpl.java:2920)
at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.setObject(PreparedStatementProxyImpl.java:411)
at com.alibaba.druid.pool.DruidPooledPreparedStatement.setObject(DruidPooledPreparedStatement.java:476)
at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.setParameters(ShardingPreparedStatement.java:188)
at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeSQL(ShardingPreparedStatement.java:163)
at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeIfNeed(ShardingPreparedStatement.java:151)
at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.getRoutedPreparedStatements(ShardingPreparedStatement.java:138)
at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.execute(ShardingPreparedStatement.java:107)

Caused by: java.io.NotSerializableException: java.io.StringReader
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
at com.mysql.jdbc.PreparedStatement.setSerializableObject(PreparedStatement.java:3876)

**Comment by dzxiang** [comment]
大家都没有碰到过这个问题吗？

**Comment by hzlzz** [comment]
我也碰到了这个问题 请问有解决方案吗

**Comment by dzxiang** [comment]
在：com.dangdang.ddframe.rdb.sharding.jdbc.adapter.AbstractPreparedStatementAdapter中临时打了一个小补丁：
    private void setParameter(final int index, final Object x) throws SQLException {
        int extendedSize = index - parameters.size();
        if (extendedSize > 1) {
            while (--extendedSize > 0) {
                parameters.add(null);
            }
        }
        if(x instanceof java.io.StringReader){
        	Reader reader = (Reader)x;
            BufferedReader r = null;
            StringBuilder b = new StringBuilder();
            String line;
            try {
            	r = new BufferedReader(reader);
            	boolean first = true;
            	String ls = System.getProperty("line.separator");
				while((line=r.readLine())!=null) {
					if(first) first = false;
					else b.append(ls);
					b.append(line);
				}
				
	            String y = b.toString();
	            parameters.add(index - 1,y);
			} catch (IOException e) {
				e.printStackTrace();
				throw new SQLException(e);
			} finally{
				if(r!=null){
					try {
						r.close();
					} catch (IOException e) {}
				}
			}
        }
        else{
        	parameters.add(index - 1, x);	
        }
    }

**Comment by billForgithub** [comment]
我也碰到了这个问题

**Comment by duran-zhu** [comment]
修复这个bug的代码会导致使用mybatis自增id出错。
在insert语句后，执行select last_insert_id() from dual出现空指针问题。

**Comment by shuohao** [comment]
我也遇到了 请问这个现在如何解决啊

**Comment by familyYuAndBo** [comment]
3.0也有这个问题，#{reqMsg,jdbcType=LONGVARCHAR}
如果是非基础类型，mysql的jdbc驱动调用了
com.mysql.cj.AbstractQueryBindings#setObject
com.mysql.cj.AbstractQueryBindings#setSerializableObject
stringReader不能序列化，抛出异常
Caused by: com.mysql.cj.exceptions.WrongArgumentException: Invalid argument value: java.io.NotSerializableException

**Comment by shenmimoon** [comment]
> 3.0也有这个问题，#{reqMsg,jdbcType=LONGVARCHAR}
> 如果是非基础类型，mysql的jdbc驱动调用了
> com.mysql.cj.AbstractQueryBindings#setObject
> com.mysql.cj.AbstractQueryBindings#setSerializableObject
> stringReader不能序列化，抛出异常
> Caused by: com.mysql.cj.exceptions.WrongArgumentException: Invalid argument value: java.io.NotSerializableException

+1

**Comment by shuohao** [comment]
对 jdbctype为longvarchar就会报这个错

**Comment by terrymanu** [comment]
**For English only**, other languages will not accept.
I just lock this issue. If you want, you can submit a new issue with English
