### ISSUE TITLE
[Improvement] 放开对其他数据库的限制，可支持标准SQL

### ISSUE THREAD

**Issue by terrymanu** [dangdangdotcom/sharding-jdbc#88]
放开对Oracle，SQLServer，DB2，PostgreSQL等数据库的支持。
但只能识别标准SQL语句，对于个性化分页等语句并不支持。

**Comment by ivanhuang0757** [comment]
hello，I try to use sharding-jdbc1.3.0 to oralce11g,but it throw a exception.Is it support other database??can u tell m how to resolve this exception?



Exception in thread "main" java.lang.ClassCastException: com.dangdang.ddframe.rdb.sharding.parser.visitor.basic.mysql.MySQLSelectVisitor cannot be cast to com.alibaba.druid.sql.dialect.oracle.visitor.OracleASTVisitor
	at com.alibaba.druid.sql.dialect.oracle.ast.stmt.OracleSelect.accept0(OracleSelect.java:58)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40)
	at com.alibaba.druid.sql.visitor.SQLASTOutputVisitor.visit(SQLASTOutputVisitor.java:770)
	at com.alibaba.druid.sql.ast.statement.SQLSelectStatement.accept0(SQLSelectStatement.java:58)
	at com.alibaba.druid.sql.ast.SQLObjectImpl.accept(SQLObjectImpl.java:40)
	at com.dangdang.ddframe.rdb.sharding.parser.SQLParseEngine.parse(SQLParseEngine.java:66)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.parseSQL(SQLRouteEngine.java:72)
	at com.dangdang.ddframe.rdb.sharding.router.SQLRouteEngine.route(SQLRouteEngine.java:67)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeSQL(ShardingPreparedStatement.java:165)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.routeIfNeed(ShardingPreparedStatement.java:160)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.getRoutedPreparedStatements(ShardingPreparedStatement.java:140)
	at com.dangdang.ddframe.rdb.sharding.jdbc.ShardingPreparedStatement.executeQuery(ShardingPreparedStatement.java:95)
	at com.dangdang.ddframe.rdb.sharding.example.jdbc.Main.printSimpleSelect(Main.java:60)
	at com.dangdang.ddframe.rdb.sharding.example.jdbc.Main.main(Main.java:46)

**Comment by Cjie2000** [comment]
![image](https://cloud.githubusercontent.com/assets/4387663/16068594/ac8219bc-32f9-11e6-943a-7eaa66b87ade.png)
Only support MySQL
